import * as cssKeywords from 'color-name';

type RGB = [number, number, number];
type HSL = [number, number, number];
type HSV = [number, number, number];
type HWB = [number, number, number];
type CMYK = [number, number, number, number];
type XYZ = [number, number, number];
type LAB = [number, number, number];
type LCH = [number, number, number];
type HEX = string;
type KEYWORD = keyof typeof cssKeywords;
type ANSI16 = number;
type ANSI256 = number;
type HCG = [number, number, number];
type APPLE = [number, number, number];

declare namespace stylizer {
    export interface Styles {
        (...text: string[]): string;

        aliceblue: Styles;
        antiquewhite: Styles;
        aqua: Styles;
        aquamarine: Styles;
        azure: Styles;
        beige: Styles;
        bisque: Styles;
        black: Styles;
        blanchedalmond: Styles;
        blue: Styles;
        blueviolet: Styles;
        brown: Styles;
        burlywood: Styles;
        cadetblue: Styles;
        chartreuse: Styles;
        chocolate: Styles;
        coral: Styles;
        cornflowerblue: Styles;
        cornsilk: Styles;
        crimson: Styles;
        cyan: Styles;
        darkblue: Styles;
        darkcyan: Styles;
        darkgoldenrod: Styles;
        darkgray: Styles;
        darkgreen: Styles;
        darkgrey: Styles;
        darkkhaki: Styles;
        darkmagenta: Styles;
        darkolivegreen: Styles;
        darkorange: Styles;
        darkorchid: Styles;
        darkred: Styles;
        darksalmon: Styles;
        darkseagreen: Styles;
        darkslateblue: Styles;
        darkslategray: Styles;
        darkslategrey: Styles;
        darkturquoise: Styles;
        darkviolet: Styles;
        deeppink: Styles;
        deepskyblue: Styles;
        dimgray: Styles;
        dimgrey: Styles;
        dodgerblue: Styles;
        firebrick: Styles;
        floralwhite: Styles;
        forestgreen: Styles;
        fuchsia: Styles;
        gainsboro: Styles;
        ghostwhite: Styles;
        gold: Styles;
        goldenrod: Styles;
        gray: Styles;
        green: Styles;
        greenyellow: Styles;
        grey: Styles;
        honeydew: Styles;
        hotpink: Styles;
        indianred: Styles;
        indigo: Styles;
        ivory: Styles;
        khaki: Styles;
        lavender: Styles;
        lavenderblush: Styles;
        lawngreen: Styles;
        lemonchiffon: Styles;
        lightblue: Styles;
        lightcoral: Styles;
        lightcyan: Styles;
        lightgoldenrodyellow: Styles;
        lightgray: Styles;
        lightgreen: Styles;
        lightgrey: Styles;
        lightpink: Styles;
        lightsalmon: Styles;
        lightseagreen: Styles;
        lightskyblue: Styles;
        lightslategray: Styles;
        lightslategrey: Styles;
        lightsteelblue: Styles;
        lightyellow: Styles;
        lime: Styles;
        limegreen: Styles;
        linen: Styles;
        magenta: Styles;
        maroon: Styles;
        mediumaquamarine: Styles;
        mediumblue: Styles;
        mediumorchid: Styles;
        mediumpurple: Styles;
        mediumseagreen: Styles;
        mediumslateblue: Styles;
        mediumspringgreen: Styles;
        mediumturquoise: Styles;
        mediumvioletred: Styles;
        midnightblue: Styles;
        mintcream: Styles;
        mistyrose: Styles;
        moccasin: Styles;
        navajowhite: Styles;
        navy: Styles;
        oldlace: Styles;
        olive: Styles;
        olivedrab: Styles;
        orange: Styles;
        orangered: Styles;
        orchid: Styles;
        palegoldenrod: Styles;
        palegreen: Styles;
        paleturquoise: Styles;
        palevioletred: Styles;
        papayawhip: Styles;
        peachpuff: Styles;
        peru: Styles;
        pink: Styles;
        plum: Styles;
        powderblue: Styles;
        purple: Styles;
        rebeccapurple: Styles;
        red: Styles;
        rosybrown: Styles;
        royalblue: Styles;
        saddlebrown: Styles;
        salmon: Styles;
        sandybrown: Styles;
        seagreen: Styles;
        seashell: Styles;
        sienna: Styles;
        silver: Styles;
        skyblue: Styles;
        slateblue: Styles;
        slategray: Styles;
        slategrey: Styles;
        snow: Styles;
        springgreen: Styles;
        steelblue: Styles;
        tan: Styles;
        teal: Styles;
        thistle: Styles;
        tomato: Styles;
        turquoise: Styles;
        violet: Styles;
        wheat: Styles;
        white: Styles;
        whitesmoke: Styles;
        yellow: Styles;
        yellowgreen: Styles;
        bgAliceblue: Styles;
        bgAntiquewhite: Styles;
        bgAqua: Styles;
        bgAquamarine: Styles;
        bgAzure: Styles;
        bgBeige: Styles;
        bgBisque: Styles;
        bgBlack: Styles;
        bgBlanchedalmond: Styles;
        bgBlue: Styles;
        bgBlueviolet: Styles;
        bgBrown: Styles;
        bgBurlywood: Styles;
        bgCadetblue: Styles;
        bgChartreuse: Styles;
        bgChocolate: Styles;
        bgCoral: Styles;
        bgCornflowerblue: Styles;
        bgCornsilk: Styles;
        bgCrimson: Styles;
        bgCyan: Styles;
        bgDarkblue: Styles;
        bgDarkcyan: Styles;
        bgDarkgoldenrod: Styles;
        bgDarkgray: Styles;
        bgDarkgreen: Styles;
        bgDarkgrey: Styles;
        bgDarkkhaki: Styles;
        bgDarkmagenta: Styles;
        bgDarkolivegreen: Styles;
        bgDarkorange: Styles;
        bgDarkorchid: Styles;
        bgDarkred: Styles;
        bgDarksalmon: Styles;
        bgDarkseagreen: Styles;
        bgDarkslateblue: Styles;
        bgDarkslategray: Styles;
        bgDarkslategrey: Styles;
        bgDarkturquoise: Styles;
        bgDarkviolet: Styles;
        bgDeeppink: Styles;
        bgDeepskyblue: Styles;
        bgDimgray: Styles;
        bgDimgrey: Styles;
        bgDodgerblue: Styles;
        bgFirebrick: Styles;
        bgFloralwhite: Styles;
        bgForestgreen: Styles;
        bgFuchsia: Styles;
        bgGainsboro: Styles;
        bgGhostwhite: Styles;
        bgGold: Styles;
        bgGoldenrod: Styles;
        bgGray: Styles;
        bgGreen: Styles;
        bgGreenyellow: Styles;
        bgGrey: Styles;
        bgHoneydew: Styles;
        bgHotpink: Styles;
        bgIndianred: Styles;
        bgIndigo: Styles;
        bgIvory: Styles;
        bgKhaki: Styles;
        bgLavender: Styles;
        bgLavenderblush: Styles;
        bgLawngreen: Styles;
        bgLemonchiffon: Styles;
        bgLightblue: Styles;
        bgLightcoral: Styles;
        bgLightcyan: Styles;
        bgLightgoldenrodyellow: Styles;
        bgLightgray: Styles;
        bgLightgreen: Styles;
        bgLightgrey: Styles;
        bgLightpink: Styles;
        bgLightsalmon: Styles;
        bgLightseagreen: Styles;
        bgLightskyblue: Styles;
        bgLightslategray: Styles;
        bgLightslategrey: Styles;
        bgLightsteelblue: Styles;
        bgLightyellow: Styles;
        bgLime: Styles;
        bgLimegreen: Styles;
        bgLinen: Styles;
        bgMagenta: Styles;
        bgMaroon: Styles;
        bgMediumaquamarine: Styles;
        bgMediumblue: Styles;
        bgMediumorchid: Styles;
        bgMediumpurple: Styles;
        bgMediumseagreen: Styles;
        bgMediumslateblue: Styles;
        bgMediumspringgreen: Styles;
        bgMediumturquoise: Styles;
        bgMediumvioletred: Styles;
        bgMidnightblue: Styles;
        bgMintcream: Styles;
        bgMistyrose: Styles;
        bgMoccasin: Styles;
        bgNavajowhite: Styles;
        bgNavy: Styles;
        bgOldlace: Styles;
        bgOlive: Styles;
        bgOlivedrab: Styles;
        bgOrange: Styles;
        bgOrangered: Styles;
        bgOrchid: Styles;
        bgPalegoldenrod: Styles;
        bgPalegreen: Styles;
        bgPaleturquoise: Styles;
        bgPalevioletred: Styles;
        bgPapayawhip: Styles;
        bgPeachpuff: Styles;
        bgPeru: Styles;
        bgPink: Styles;
        bgPlum: Styles;
        bgPowderblue: Styles;
        bgPurple: Styles;
        bgRebeccapurple: Styles;
        bgRed: Styles;
        bgRosybrown: Styles;
        bgRoyalblue: Styles;
        bgSaddlebrown: Styles;
        bgSalmon: Styles;
        bgSandybrown: Styles;
        bgSeagreen: Styles;
        bgSeashell: Styles;
        bgSienna: Styles;
        bgSilver: Styles;
        bgSkyblue: Styles;
        bgSlateblue: Styles;
        bgSlategray: Styles;
        bgSlategrey: Styles;
        bgSnow: Styles;
        bgSpringgreen: Styles;
        bgSteelblue: Styles;
        bgTan: Styles;
        bgTeal: Styles;
        bgThistle: Styles;
        bgTomato: Styles;
        bgTurquoise: Styles;
        bgViolet: Styles;
        bgWheat: Styles;
        bgWhite: Styles;
        bgWhitesmoke: Styles;
        bgYellow: Styles;
        bgYellowgreen: Styles;
        bold: Styles;
        dim: Styles;
        italic: Styles;
        underline: Styles;
        inverse: Styles;
        hidden: Styles;
        strikethrough: Styles;

        rgb(rgb: RGB): Styles;
        hsl(hsl: HSL): Styles;
        hsv(hsv: HSV): Styles;
        hwb(hwb: HWB): Styles;
        cmyk(cmyk: CMYK): Styles;
        xyz(xyz: XYZ): Styles;
        lab(lab: LAB): Styles;
        lch(lch: LCH): Styles;
        hex(hex: HEX): Styles;
        keyword(keyword: KEYWORD): Styles;
        ansi16(code: ANSI16): Styles;
        ansi256(code: ANSI256): Styles;
        hcg(hcg: HCG): Styles;
        apple(apple: APPLE): Styles;
        gray(gray: GRAY): Styles;
        bgRgb(rgb: RGB): Styles;
        bgHsl(hsl: HSL): Styles;
        bgHsv(hsv: HSV): Styles;
        bgHwb(hwb: HWB): Styles;
        bgCmyk(cmyk: CMYK): Styles;
        bgXyz(xyz: XYZ): Styles;
        bgLab(lab: LAB): Styles;
        bgLch(lch: LCH): Styles;
        bgHex(hex: HEX): Styles;
        bgKeyword(keyword: KEYWORD): Styles;
        bgAnsi16(code: ANSI16): Styles;
        bgAnsi256(code: ANSI256): Styles;
        bgHcg(hcg: HCG): Styles;
        bgApple(apple: APPLE): Styles;
        bgGray(gray: GRAY): Styles;
    }
}

declare const stylizer: stylizer.Styles;

export = stylizer;